### ISSUE TITLE
Publish artifacts to maven repository

### ISSUE THREAD

**Issue by zackangelo** [constantcontact/java-sdk#27]
Is there a reason there aren't any artifacts published to a central Maven repository? Makes it somewhat cumbersome to get up and running with the Java SDK.

**Comment by csciuto** [comment]
Process is here: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by dwelch2344** [comment]
+1 to this. Otherwise you're putting it on consumers to a) install it to a project-specific repo b) install it to a  company / self-hosted repository, or c) build from source

None of these are appealing, and (IME) most small teams can't do the first two

**Comment by dwelch2344** [comment]
Ended up throwing it in a personal repository for the time being. Unless you Constant Contact guys have qualms with it, I'll share it here for any other lasy devs :) 
```
<repository> 		
<id>dwelch-repo</id> 		
<url>https://github.com/dwelch2344/maven-repo/raw/master/releases</url> 	
</repository> 	
<repository> 		
<id>dwelch-snapshot-repo</id> 		
<url>https://github.com/dwelch2344/maven-repo/raw/master/snapshots</url> 		
<snapshots> </snapshots> 	
</repository> 
```

**Comment by csciuto** [comment]
Sorry this has been open for 18 months, but this work has been completed. Let me know if there are any issues!

https://search.maven.org/#artifactdetails|com.constantcontact|constantcontact|4.2.0|jar
