### ISSUE TITLE
open source forgebiz-sync

### ISSUE THREAD

**Issue by rhodebump** [constantcontact/java-sdk#43]
I just wanted to note that I used this excellent library to write a service that syncs Microsoft Retail POS with constant contact.
Apache license and open source
https://github.com/rhodebump/forgebiz-sync

If you guys put together a wiki page of users, I wouldn't mind being listed!

Thanks
![forgebiz-logo](https://cloud.githubusercontent.com/assets/154073/5350328/80943990-7f11-11e4-9ee8-e776acbd122c.png)

**Comment by csciuto** [comment]
This was placed in the Marketplace @ http://marketplace.constantcontact.com/Listing/applications/forgebiz/PML-51218

Thanks gains @rhodebump
