### ISSUE TITLE
Cannot close inputstream after call bulkContactUploadMultipart

### ISSUE THREAD

**Issue by wjdhamilton** [constantcontact/java-sdk#53]
Hi,

I have been having a few issues with using the api for uploading xls files. Basically, we have a large number of repetitive eMails going out and I have built an app that streamlines the uploading of the lists. 

I note that addBulkContactsMultipart opens a fileinputstream, which is then used in MutipartBuilder.buildMultipartBody, but it is not closed meaning the file remains locked after the method has returned. Shouldn't the filestream be closed after the filestream has been consumed?

Cheers,

James

**Comment by csciuto** [comment]
You are correct, that is a defect. I'll forward along to the appropriate resources.

Thanks for bringing this to our attention!

**Comment by ggrell** [comment]
NPTF, obsolete.
