### ISSUE TITLE
Birthday_Month and Birthday_Day are missing from the ContactData class

### ISSUE THREAD

**Issue by perelman** [constantcontact/java-sdk#66]
Hi all the bulk activity import contacts support Birthday_Month and Birthday_Day fields.
And ContactData miss them i think.
Thanks
Yuval

**Comment by egaiter** [comment]
Hi Yuval,

Thanks for reporting this. I've got a busy day today, but I'm hopeful that we can have a fix for this built and merged before the end of next week.

Elijah Gaiter
API Support Engineer
Constant Contact

**Comment by csciuto** [comment]
BIRTHDAY_DAY
BIRTHDAY_MONTH
do appear to be missing, as is
ANNIVERSARY

**Comment by csciuto** [comment]
See http://developer.constantcontact.com/docs/bulk_activities_api/bulks-activities-import-contacts-api.html
